- name: Install nvidia drivers
  ansible.builtin.package:
    name:
    - nvidia-headless-535-server
    - nvidia-utils-535-server
    state: present

- name: Check if NVIDIA GPU device is present
  ansible.builtin.stat:
    path: /dev/nvidia0
  register: nvidia_device

- name: Check NVIDIA persistence mode
  ansible.builtin.command:
    cmd: nvidia-smi --query-gpu=persistence_mode --format=csv,noheader
  register: nvidia_persistence
  changed_when: false
  ignore_errors: true
  when: nvidia_device.stat.exists

- name: Set NVIDIA persistence mode
  ansible.builtin.shell:
    cmd: nvidia-smi --persistence-mode=ENABLED
  changed_when: true
  when:
  - nvidia_device.stat.exists
  - nvidia_persistence is not skipped
  - "'Enabled' not in nvidia_persistence.stdout"
